### ISSUE TITLE
brackets are the wrong way round when text is selected backwards

### ISSUE THREAD

**Issue by regr4** [deusnefum/micro-quoter#1]
I think this can be easily solved by adding an if statement in the `quote` function which switches the locations where the chars are inserted around if the location of `-bp.Cursor.CurSelection[1]` is greater than `-bp.Cursor.CurSelection[2]`. There is a function for this called [Loc.GreaterThan](https://godoc.org/github.com/zyedidia/micro/internal/buffer#Loc.GreaterThan) 
I'll make a pull request to fix it soon.

**Comment by sparques** [comment]
I don't know how I missed this, but thanks for the bug find and fix, I'll merge and bump the release.
